INSERT INTO `boardgames`.`mechanics` (`id_mechanics`, `name`, `description`) VALUES
(1, 'Worker Placement', 'Gracze przydzielają swoich pracowników do różnych zadań lub miejsc na planszy, aby uzyskać zasoby lub wykonać akcje.'),
(2, 'Deck Building', 'Gracze budują własne talie kart podczas gry, kupując nowe karty, które dodają do swoich talii.'),
(3, 'Area Control', 'Gracze rywalizują o kontrolę nad określonymi obszarami na planszy, zdobywając punkty za dominację w tych regionach.'),
(4, 'Tile Placement', 'Gracze układają kafelki na planszy, tworząc różne układy, które przynoszą korzyści lub punkty.'),
(5, 'Drafting', 'Gracze wybierają karty lub inne elementy z ograniczonej puli, starając się optymalizować swoje wybory względem strategii.'),
(6, 'Set Collection', 'Gracze zbierają zestawy kart lub innych elementów, które przynoszą punkty lub specjalne zdolności, gdy są skompletowane.'),
(7, 'Role Playing', 'Gracze wcielają się w postacie z unikalnymi zdolnościami i wykonują różne zadania w fabularnym kontekście.'),
(8, 'Dice Rolling', 'Gracze używają kości do określania wyników akcji, wpływając na strategię poprzez losowość.'),
(9, 'Cooperative Play', 'Gracze współpracują, aby osiągnąć wspólny cel, rywalizując z mechanikami gry, a nie między sobą.'),
(10, 'Resource Management', 'Gracze zarządzają ograniczonymi zasobami, aby jak najefektywniej realizować cele i zdobywać punkty.'),
(11, 'Hand Management', 'Gracze zarządzają swoimi kartami, starając się optymalnie wykorzystać ich zdolności i efekty.'),
(12, 'Variable Player Powers', 'Każdy gracz ma unikalne zdolności lub cechy, które wpływają na strategię gry.'),
(13, 'Hidden Movement', 'Ruchy jednego lub kilku graczy są ukryte przed innymi, co dodaje element niepewności i dedukcji.'),
(14, 'Grid Movement', 'Gracze poruszają swoje pionki po planszy składającej się z siatki pól, planując ruchy strategicznie.'),
(15, 'Pattern Building', 'Gracze starają się tworzyć określone wzory na planszy, aby zdobywać punkty lub osiągać cele.'),
(16, 'Campaign/Legacy', 'Gracze rozgrywają wiele scenariuszy, a ich decyzje mają trwały wpływ na przyszłe rozgrywki.'),
(17, 'Storytelling', 'Gra koncentruje się na narracji, a gracze wspólnie tworzą historię poprzez swoje decyzje.'),
(18, 'Auction/Bidding', 'Gracze licytują przedmioty lub akcje, starając się zdobyć je za jak najniższą cenę.'),
(19, 'Real-Time', 'Gracze wykonują akcje jednocześnie lub w określonym limicie czasu.'),
(20, 'Pick-up and Deliver', 'Gracze transportują zasoby z jednego miejsca na inne, zdobywając za to punkty.'),
(21, 'Modular Board', 'Plansza gry składa się z modułów, które można układać w różny sposób, tworząc różne układy.'),
(22, 'Betting/Wagering', 'Gracze obstawiają wyniki różnych zdarzeń w grze.'),
(23, 'Memory', 'Gracze muszą pamiętać informacje, aby skutecznie podejmować decyzje.'),
(24, 'Simulation', 'Gra stara się wiernie odwzorować rzeczywiste lub fikcyjne systemy i ich działanie.'),
(25, 'Trick-taking', 'Gracze starają się wygrywać rundy (lewy) poprzez zagrywanie kart o wyższej wartości.'),
(26, 'Press Your Luck', 'Gracze decydują, czy kontynuować ryzykowne akcje, zyskując więcej lub tracąc wszystko.'),
(27, 'Variable Setup', 'Gra oferuje różne początkowe ustawienia, co zwiększa regrywalność.'),
(28, 'Asymmetric Gameplay', 'Każdy gracz ma inne zdolności, cele lub zasoby, co prowadzi do różnorodnych strategii.'),
(29, 'Time Track', 'Czas gry jest zarządzany poprzez specjalny tor lub mechanizm, wpływający na dostępne akcje.'),
(30, 'Action Points', 'Gracze mają określoną liczbę punktów akcji do wykorzystania w swojej turze, które mogą przeznaczyć na różne działania.');