INSERT INTO `boardgames`.`publisher` (`id_publisher`, `name`) VALUES
(1, 'Column2'),
(2, 'Kosmos'),
(3, 'Z-Man Games'),
(4, 'Days of Wonder'),
(5, 'Hans im Glück'),
(6, 'Rio Grande Games'),
(7, 'Repos Production'),
(8, 'Stronghold Games'),
(9, 'Cephalofair Games'),
(10, 'Plan B Games'),
(11, 'Stonemaier Games'),
(12, 'Alea'),
(13, 'Space Cowboys'),
(14, 'Czech Games Edition'),
(15, 'FryxGames'),
(16, 'Leder Games'),
(17, 'Lookout Games'),
(18, 'GMT Games'),
(19, 'North Star Games'),
(20, 'Starling Games'),
(21, 'Ravensburger'),
(22, 'Cool Mini or Not'),
(23, 'Libellud'),
(24, 'Roxley Games'),
(25, 'Renegade Game Studios'),
(26, 'Greater Than Games'),
(27, 'Portal Games'),
(28, 'Next Move Games'),
(29, 'Eagle-Gryphon Games'),
(30, 'The City of Games'),
(31, 'Fantasy Flight Games'),
(32, 'Avalon Hill'),
(33, 'Mayfair Games'),
(34, 'Awaken Realms'),
(35, 'Eggertspiele'),
(36, 'PD-Verlag'),
(37, 'Garphill Games'),
(38, 'Mindclash Games'),
(39, 'Lautapelit.fi'),
(40, 'Lucky Duck Games'),
(41, 'Matagot'),
(42, 'CMON Limited'),
(43, 'Giochi Uniti'),
(44, 'Pegasus Spiele'),
(45, 'Capstone Games'),
(46, 'Pandasaurus Games'),
(47, 'Indie Boards & Cards'),
(48, 'Alderac Entertainment Group'),
(49, 'Plaid Hat Games'),
(50, 'Deep Water Games'),
(51, 'IELLO'),
(52, 'Asmadi Games'),
(53, 'White Wizard Games'),
(54, 'Bezier Games'),
(55, 'Fireside Games'),
(56, 'WizKids'),
(57, 'FryxGames'),
(58, 'Lookout Games'),
(59, 'Renegade Game Studios'),
(60, 'Plan B Games'),
(61, 'Mindclash Games'),
(62, 'Next Move Games'),
(63, 'Garphill Games'),
(64, 'Days of Wonder'),
(65, 'Fantasy Flight Games'),
(66, 'Capstone Games'),
(67, 'Roxley Games'),
(68, 'Awaken Realms'),
(69, 'Pandasaurus Games'),
(70, 'CMON Limited'),
(71, 'Deep Water Games'),
(72, 'Rio Grande Games');
