INSERT INTO `boardgames`.`games` (`name`, `description`, `min_players`, `max_players`, `play_time`, `complexity`) VALUES
('Catan', 'Gra ekonomiczna, w której gracze zasiedlają wyspę Catan, zbierają surowce i handlują nimi.', 3, 4, 90, 2.5),
('Pandemic', 'Gra kooperacyjna, w której gracze wspólnie walczą z globalnymi epidemiami.', 2, 4, 60, 2.4),
('Ticket to Ride', 'Gra planszowa o budowaniu linii kolejowych w Ameryce Północnej.', 2, 5, 60, 1.9),
('Carcassonne', 'Gra kafelkowa, w której gracze budują miasta, drogi i klasztory.', 2, 5, 45, 1.8),
('Dominion', 'Gra karciana, w której gracze budują swoje talie kart podczas gry.', 2, 4, 30, 2.6),
('7 Wonders', 'Gra karciana, w której gracze rozwijają cywilizacje przez trzy epoki.', 2, 7, 30, 2.3),
('Terraforming Mars', 'Gra strategiczna, w której gracze przekształcają Marsa w planetę zdatną do życia.', 1, 5, 120, 3.2),
('Gloomhaven', 'Gra taktyczna z elementami RPG, gdzie gracze walczą z potworami i zdobywają skarby.', 1, 4, 120, 3.8),
('Azul', 'Gra abstrakcyjna, w której gracze układają płytki w piękne mozaiki.', 2, 4, 45, 1.9),
('Wingspan', 'Gra o zarządzaniu ptasim rezerwatem, w której gracze zbierają ptaki i zdobywają punkty.', 1, 5, 70, 2.5),
('The Castles of Burgundy', 'Gra strategiczna o budowaniu zamków i zarządzaniu zasobami w średniowiecznej Burgundii.', 2, 4, 90, 3.0),
('Splendor', 'Gra ekonomiczna, w której gracze zbierają kamienie szlachetne i kupują karty rozwoju.', 2, 4, 30, 1.8),
('Codenames', 'Gra towarzyska, w której gracze odgadują tajne hasła na podstawie wskazówek.', 2, 8, 15, 1.5),
('Scythe', 'Gra strategiczna osadzona w alternatywnej Europie lat 20. XX wieku, gdzie gracze rywalizują o dominację.', 1, 7, 115, 3.4),
('Terraforming Mars: Ares Expedition', 'Karciana wersja gry Terraforming Mars, w której gracze rywalizują o terraformowanie Marsa.', 1, 4, 60, 2.9),
('Root', 'Asymetryczna gra strategiczna, w której różne frakcje walczą o kontrolę nad lasem.', 2, 4, 90, 3.7),
('Agricola', 'Gra ekonomiczna, w której gracze zarządzają farmą, sadzą zboże i hodują zwierzęta.', 1, 5, 120, 3.6),
('Twilight Struggle', 'Gra strategiczna osadzona w okresie zimnej wojny, gdzie gracze reprezentują USA i ZSRR.', 2, 2, 180, 3.7),
('The Quacks of Quedlinburg', 'Gra o warzeniu eliksirów, w której gracze losują składniki z woreczków, starając się uniknąć wybuchów.', 2, 4, 45, 2.0),
('Everdell', 'Gra o zarządzaniu zasobami i budowaniu miasta w lesie Everdell.', 1, 4, 80, 2.8),
('Puerto Rico', 'Gra ekonomiczna, w której gracze zarządzają plantacjami i eksportują towary.', 2, 5, 90, 3.3),
('Blood Rage', 'Gra strategiczna osadzona w mitologii nordyckiej, gdzie gracze kierują klanami wikingów w Ragnaroku.', 2, 4, 90, 2.9),
('Viticulture', 'Gra ekonomiczna o uprawie winorośli i produkcji wina w Toskanii.', 1, 6, 90, 2.8),
('Dixit', 'Gra towarzyska, w której gracze interpretują abstrakcyjne ilustracje i próbują odgadnąć karty innych graczy.', 3, 6, 30, 1.2),
('Lost Ruins of Arnak', 'Gra przygodowa, w której gracze eksplorują tajemniczą wyspę, szukając artefaktów i skarbów.', 1, 4, 90, 2.9),
('Brass: Birmingham', 'Gra ekonomiczna osadzona w czasach rewolucji przemysłowej, gdzie gracze rozwijają przemysł i handel.', 2, 4, 120, 3.9),
('Clank!', 'Gra przygodowa, w której gracze kradną skarby ze smoczej jaskini, starając się uniknąć obudzenia smoka.', 2, 4, 60, 2.3),
('Spirit Island', 'Gra kooperacyjna, w której gracze jako duchy bronią wyspę przed kolonizatorami.', 1, 4, 120, 4.0),
('Gaia Project', 'Gra strategiczna, w której gracze rozwijają kosmiczne cywilizacje, terraformując planety i budując struktury.', 1, 4, 150, 4.3),
('Patchwork', 'Gra logiczna dla dwóch graczy, w której układają oni fragmenty materiału na swoich planszach, tworząc koce.', 2, 2, 30, 1.6),
('The Crew: The Quest for Planet Nine', 'Kooperacyjna gra karciana, w której gracze wspólnie realizują misje w kosmosie.', 2, 5, 20, 1.9),
('Kingdomino', 'Gra strategiczna, w której gracze budują swoje królestwa, dobierając i układając kafelki domino.', 2, 4, 15, 1.4),
('On Mars', 'Gra strategiczna, w której gracze jako koloniści rozwijają i terraformują Marsa.', 1, 4, 150, 4.6),
('The Isle of Cats', 'Gra o ratowaniu kotów z wyspy przed nadchodzącą katastrofą, gdzie gracze zbierają i układają karty.', 1, 4, 90, 2.9),
('Mansions of Madness: Second Edition', 'Gra przygodowa z elementami horroru, w której gracze eksplorują nawiedzone posiadłości, rozwiązując zagadki.', 1, 5, 120, 3.6),
('Betrayal at House on the Hill', 'Gra przygodowa, w której gracze eksplorują nawiedzony dom, z jednym z graczy zdradzającym resztę.', 3, 6, 60, 2.5),
('Caverna: The Cave Farmers', 'Gra ekonomiczna, w której gracze zarządzają rodziną krasnoludów, uprawiając ziemię i eksplorując jaskinie.', 1, 7, 120, 3.8),
('Sherlock Holmes Consulting Detective', 'Gra detektywistyczna, w której gracze rozwiązują zagadki kryminalne w wiktoriańskim Londynie.', 1, 8, 120, 2.6),
('Tainted Grail: The Fall of Avalon', 'Gra przygodowa, w której gracze odkrywają mroczny świat Avalonu, podejmując decyzje wpływające na rozwój fabuły.', 1, 4, 180, 4.1),
('Great Western Trail', 'Gra strategiczna, w której gracze przewożą bydło z Teksasu do Kansas City, zarabiając pieniądze i zdobywając punkty.', 2, 4, 150, 3.7),
('Concordia', 'Gra ekonomiczna, w której gracze rozwijają handel i budują imperia w starożytnym Rzymie.', 2, 5, 100, 3.1),
('Architects of the West Kingdom', 'Gra strategiczna, w której gracze zarządzają zasobami i budują struktury w średniowiecznym królestwie.', 1, 5, 80, 2.8),
('Paladins of the West Kingdom', 'Gra strategiczna, w której gracze rekrutują paladynów i rozwijają swoje miasta w obliczu zbliżających się wrogów.', 1, 4, 90, 3.5),
('Raiders of the North Sea', 'Gra strategiczna, w której gracze jako wikingowie rabują wioski i gromadzą zasoby.', 2, 4, 80, 2.6),
('Anachrony', 'Gra strategiczna osadzona w postapokaliptycznym świecie, gdzie gracze manipulują czasem, aby zdobywać zasoby.', 1, 4, 120, 4.2),
('Brass: Lancashire', 'Gra ekonomiczna osadzona w czasach rewolucji przemysłowej w Anglii, gdzie gracze rozwijają przemysł i handel.', 2, 4, 120, 3.9),
('Race for the Galaxy', 'Gra karciana, w której gracze rozwijają galaktyczne cywilizacje, odkrywając planety i budując technologie.', 2, 4, 60, 2.9),
('Eclipse', 'Gra strategiczna osadzona w kosmosie, gdzie gracze rozwijają swoje cywilizacje, eksplorują i walczą.', 2, 6, 180, 3.6),
('Robinson Crusoe: Adventures on the Cursed Island', 'Gra kooperacyjna, w której gracze starają się przetrwać na bezludnej wyspie, realizując różne scenariusze.', 1, 4, 120, 3.8),
('Chronicles of Crime', 'Gra detektywistyczna, w której gracze rozwiązują zagadki kryminalne przy użyciu technologii VR i aplikacji mobilnej.', 1, 4, 90, 2.3),
('Tapestry', 'Gra cywilizacyjna, w której gracze prowadzą swoje cywilizacje przez epoki, rozwijając technologie i kulturę.', 1, 5, 120, 3.9),
('Wingspan European Expansion', 'Rozszerzenie do gry Wingspan, wprowadzające nowe gatunki ptaków występujące w Europie.', 1, 5, 70, 2.6),
('Anno 1800', 'Gra ekonomiczna, w której gracze budują i zarządzają miastami w okresie rewolucji przemysłowej.', 2, 4, 120, 3.4),
('Arkham Horror: The Card Game', 'Gra karciana osadzona w świecie H.P. Lovecrafta, w której gracze eksplorują miasto Arkham i walczą z nadprzyrodzonymi bytami.', 1, 2, 60, 3.2),
('Mage Knight', 'Gra strategiczna osadzona w fantastycznym świecie, w której gracze wcielają się w magów walczących o kontrolę nad terytorium.', 1, 4, 240, 4.5),
('Root: The Underworld Expansion', 'Rozszerzenie do gry Root, dodające dwie nowe frakcje oraz nowe możliwości rozgrywki.', 2, 6, 90, 3.8),
('Brass: Lancashire - Iron Clays', 'Zestaw żetonów do gry Brass: Lancashire, zaprojektowany w celu ułatwienia rozgrywki i podniesienia jakości komponentów.', 2, 4, 120, 3.0),
('Everdell: Pearlbrook', 'Rozszerzenie do gry Everdell, wprowadzające nowe miejsca, postacie i zasoby, związane z podwodnym światem Pearlbrook.', 1, 4, 60, 3.1),
('Scythe: The Rise of Fenris', 'Rozszerzenie do gry Scythe, wprowadzające kampanię fabularną oraz nowe elementy rozgrywki.', 1, 7, 90, 3.7),
('Marvel Champions: The Card Game', 'Gra karciana, w której gracze wcielają się w superbohaterów z uniwersum Marvela, walcząc z przeciwnikami i rozwiązując misje.', 1, 4, 60, 3.0),
('Terra Mystica', 'Gra strategiczna, w której gracze kierują frakcjami fantazyjnych ras, rozbudowując swoje osady i walcząc o kontrolę nad terenami.', 2, 5, 150, 3.8),
('A Feast for Odin', 'Gra ekonomiczna, w której gracze jako wikingowie zajmują się rolnictwem, handlem i odkrywaniem nowych ziem.', 1, 4, 120, 3.9),
('Twilight Imperium', 'Gra strategiczna osadzona w przestrzeni kosmicznej, w której gracze rywalizują o kontrolę nad galaktyką poprzez politykę, handel i wojnę.', 3, 6, 480, 4.5),
('Through the Ages: A New Story of Civilization', 'Gra cywilizacyjna, w której gracze kierują swoimi cywilizacjami przez różne epoki, rozwijając technologię, kulturę i wpływy.', 2, 4, 240, 4.0),
('Star Wars: Rebellion', 'Gra strategiczna osadzona w świecie Gwiezdnych Wojen, w której gracze kierują siłami Imperium lub Rebelii, walcząc o kontrolę nad galaktyką.', 2, 4, 240, 4.3),
('Pax Pamir: Second Edition', 'Gra strategiczna osadzona w Afganistanie XIX wieku, w której gracze rywalizują o wpływy w regionie poprzez intrygi, politykę i wojnę.', 1, 5, 120, 3.5),
('Vinhos Deluxe Edition', 'Gra ekonomiczna o produkcji wina w Portugalii, w której gracze zarządzają swoimi winnicami i winiarniami, starając się zdobyć jak najwięcej punktów.', 1, 4, 135, 3.6),
('Battlestar Galactica: The Board Game', 'Gra kooperacyjna osadzona w świecie Battlestar Galactica, w której gracze walczą o przetrwanie ludzkości na pokładzie statku kosmicznego, starając się odkryć i wyeliminować zdrajcę.', 3, 6, 180, 4.1),
('Teotihuacan: City of Gods', 'Gra strategiczna osadzona w starożytnym Meksyku, w której gracze budują i rozwijają miasto Teotihuacan, rywalizując o wpływy i punkty zwycięstwa.', 1, 4, 120, 3.7),
('Tzolk in: The Mayan Calendar', 'Gra ekonomiczna, w której gracze zarządzają plemionami Majów, rozwijając swoje osady, budując piramidy i organizując rytuały.', 2, 4, 90, 3.4),
('Mage Wars Arena', 'Gra taktyczna, w której gracze wcielają się w potężnych magów, rywalizujących ze sobą w magicznych pojedynkach.', 2, 4, 90, 3.2),
('Imperial Settlers', 'Gra karciana, w której gracze budują swoje cywilizacje, rozwijając swoje osady i zdobywając surowce.', 1, 4, 90, 3.0),
('Nemesis', 'Gra przygodowa osadzona na pokładzie statku kosmicznego, w której gracze walczą o przetrwanie, jednocześnie próbując odkryć swoje własne cele i tajemnice.', 1, 5, 180, 4.4),
('Brass: Lancashire', 'Gra ekonomiczna osadzona w czasach rewolucji przemysłowej w Anglii, gdzie gracze rozwijają przemysł i handel.', 2, 4, 120, 3.9),
('Star Wars: X-Wing Miniatures Game', 'Gra bitewna osadzona w świecie Gwiezdnych Wojen, w której gracze rywalizują ze sobą pilotując statki kosmiczne, starając się zniszczyć flotę przeciwnika.', 2, 4, 45, 3.1),
('Dune', 'Gra strategiczna osadzona w świecie powieści Franka Herberta, w której gracze rywalizują o kontrolę nad planetą Arrakis poprzez politykę, negocjacje i wojnę.', 2, 6, 180, 4.3),
('Aeon`s End', 'Gra kooperacyjna, w której gracze bronią miasta przed inwazją potężnych istot zwanymi Nemesis.', 1, 4, 60, 3.2),
('Tigris & Euphrates', 'Gra strategiczna, w której gracze rywalizują o kontrolę nad starożytnymi królestwami, rozwijając swoje cywilizacje.', 2, 4, 90, 3.5),
('The Crew: Mission Deep Sea', 'Rozszerzenie do gry The Crew: The Quest for Planet Nine, wprowadzające nowe misje i elementy rozgrywki osadzone pod wodą.', 2, 5, 20, 2.0),
('Marvel Champions: The Rise of Red Skull', 'Rozszerzenie do gry Marvel Champions, dodające nowe postacie i wrogów, w tym Czerwony Czaszkę.', 1, 4, 60, 3.2),
('Nemesis Lockdown', 'Samodzielne rozszerzenie do gry Nemesis, które przenosi graczy na pokład stacji kosmicznej pełnej niebezpieczeństw.', 1, 5, 180, 4.5),
('Dune Imperium', 'Gra strategiczna osadzona w świecie Dune, w której gracze rywalizują o kontrolę nad planetą Arrakis poprzez politykę, handel i walkę.', 1, 4, 120, 3.8),
('Lost Ruins of Arnak: Expedition Leaders', 'Rozszerzenie do gry Lost Ruins of Arnak, dodające nowe karty liderów z unikalnymi zdolnościami.', 1, 4, 90, 3.0),
('The Voyages of Marco Polo', 'Gra strategiczna, w której gracze wcielają się w podróżników wędrujących po średniowiecznej Azji, handlując towarami i rozwijając miasta.', 2, 4, 100, 3.6),
('Gaia Project: A Project Terraforming Mars Game', 'Kolejna część gry Gaia Project, przenosząca mechanikę z Gaia Project na tereny Marsa.', 1, 4, 150, 4.4),
('The Gallerist', 'Gra ekonomiczna, w której gracze wcielają się w właścicieli galerii sztuki, spekulując na rynku sztuki i promując artystów.', 1, 4, 120, 4.0),
('War of the Ring', 'Gra strategiczna osadzona w Śródziemiu, w której gracze rywalizują o losy Pierścienia Władzy, prowadząc armie Wolnych Ludzi lub Saurona.', 2, 4, 180, 4.7),
('Brass: Birmingham – Roxley Games Edition', 'Nowsza wersja gry Brass: Birmingham, zawierająca ulepszone komponenty i korekty w zasadach.', 2, 4, 120, 4.0),
('Nemesis: Aftermath', 'Samodzielne rozszerzenie do gry Nemesis, które przenosi akcję na zniszczony pokład statku kosmicznego i dodaje nowe wyzwania.', 1, 5, 180, 4.6),
('Cthulhu: Death May Die', 'Gra kooperacyjna osadzona w uniwersum H.P. Lovecrafta, w której gracze walczą z przerażającymi istotami starając się zapobiec nadejściu Cthulhu.', 1, 5, 90, 3.6),
('Underwater Cities', 'Gra strategiczna, w której gracze budują podwodne miasta, rozwijając infrastrukturę i zaspokajając potrzeby mieszkańców.', 1, 4, 150, 3.8),
('Arkham Horror: Third Edition', 'Gra kooperacyjna osadzona w świecie H.P. Lovecrafta, w której gracze badają miasto Arkham, próbując zapobiec nadejściu starożytnych bytów.', 1, 6, 120, 3.5),
('Star Wars: Outer Rim', 'Gra osadzona w świecie Gwiezdnych Wojen, w której gracze wcielają się w łowców nagród, podróżując po peryferiach galaktyki w poszukiwaniu sławy i fortuny.', 1, 4, 120, 3.3),
('Anachrony: Fractures of Time', 'Rozszerzenie do gry Anachrony, które wprowadza nowe mechaniki związane z podróżami w czasie oraz dodaje nowe karty i budynki.', 1, 4, 120, 4.3),
('Root: Clockwork Expansion', 'Rozszerzenie do gry Root, dodające zautomatyzowane frakcje, które mogą zastępować graczy w rozgrywce.', 2, 6, 90, 3.8),
('Pandemic Legacy: Season 2', 'Drugie sezonowe rozszerzenie do gry Pandemic, które przenosi akcję do postapokaliptycznego świata, gdzie gracze próbują odbudować cywilizację po globalnej pandemii.', 2, 4, 60, 3.9),
('Eclipse: Second Dawn for the Galaxy', 'Gra strategiczna osadzona w kosmosie, w której gracze rywalizują o kontrolę nad galaktyką poprzez kolonizację, handel i walkę.', 2, 6, 120, 4.0),
('Terraforming Mars: Prelude', 'Rozszerzenie do gry Terraforming Mars, które wprowadza karty początkowe, umożliwiające szybsze rozpoczęcie terraformowania planety.', 1, 5, 90, 3.0),
('Gloomhaven: Jaws of the Lion', 'Samodzielne rozszerzenie do gry Gloomhaven, zawierające skondensowaną kampanię, idealną dla nowych graczy.', 1, 4, 50, 3.7),
('7 Wonders Duel: Pantheon', 'Rozszerzenie do gry 7 Wonders Duel, wprowadzające bogów i boginie, którzy oferują specjalne zdolności.', 2, 2, 30, 2.8),
('Spirit Island: Branch & Claw', 'Rozszerzenie do gry Spirit Island, dodające nowe duchy, karty mocy i mechaniki związane z fauną i florą.', 1, 4, 120, 3.6),
('Wingspan: European Expansion', 'Rozszerzenie do gry Wingspan, wprowadzające europejskie ptaki, nowe karty kart mocy i nowe plansze.', 1, 5, 70, 3.2),
('Twilight Imperium: Fourth Edition', 'Gra strategiczna osadzona w kosmosie, w której gracze rywalizują o kontrolę nad galaktyką poprzez politykę, handel i wojnę.', 3, 6, 240, 4.8),
('Dominion: Intrigue', 'Rozszerzenie do gry Dominion, które dodaje nowe karty królestwa oraz karty akcji, umożliwiające bardziej interaktywną rozgrywkę.', 2, 4, 30, 2.6),
('Azul: Summer Pavilion', 'Kolejna część serii Azul, w której gracze układają kafelki na planszy, starając się zdobyć jak najwięcej punktów.', 2, 4, 45, 2.3),
('Wingspan: Oceania Expansion', 'Rozszerzenie do gry Wingspan, wprowadzające ptaki z regionu Oceanii, nowe karty akcji i nowe plansze.', 1, 5, 70, 3.2),
('Azul: Stained Glass of Sintra', 'Druga część serii Azul, w której gracze układają kolorowe szkła w witraże.', 2, 4, 45, 2.2),
('Everdell: Spirecrest', 'Rozszerzenie do gry Everdell, wprowadzające nowe miejsca i mechaniki związane z górskimi terenami.', 1, 4, 80, 3.0),
('Nemesis: Carnomorphs', 'Rozszerzenie do gry Nemesis, dodające nową frakcję wrogów - Carnomorphs.', 1, 5, 180, 4.5),
('Caverna: Cave vs Cave', 'Dwuosobowa wersja gry Caverna, w której gracze zarządzają krasnoludzkimi rodzinami w jaskiniach.', 2, 2, 40, 2.1),
('Terraforming Mars: Colonies', 'Rozszerzenie do gry Terraforming Mars, wprowadzające kolonie na innych ciałach niebieskich.', 1, 5, 120, 3.2),
('Gloomhaven: Forgotten Circles', 'Rozszerzenie do gry Gloomhaven, dodające nowe scenariusze, postacie i przedmioty.', 1, 4, 120, 3.9),
('Viticulture: Tuscany Essential Edition', 'Rozszerzenie do gry Viticulture, wprowadzające nowe plansze, karty i mechaniki.', 1, 6, 90, 3.1),
('Eclipse: Ship Pack One', 'Rozszerzenie do gry Eclipse, dodające nowe statki i technologie.', 2, 6, 180, 3.5),
('Robinson Crusoe: Treasure Chest', 'Rozszerzenie do gry Robinson Crusoe, wprowadzające nowe scenariusze i przedmioty.', 1, 4, 120, 3.8),
('Clans of Caledonia', 'Gra ekonomiczna, w której gracze zarządzają klanami w Szkocji, produkując towary i handlując nimi.', 1, 4, 120, 3.3),
('The Pursuit of Happiness', 'Gra planszowa, w której gracze zarządzają życiem swoich postaci, podejmując decyzje związane z pracą, relacjami i hobby.', 1, 4, 90, 2.5),
('Obsession', 'Gra ekonomiczna osadzona w wiktoriańskiej Anglii, w której gracze zarządzają arystokratycznymi posiadłościami i organizują przyjęcia.', 1, 4, 90, 3.0),
('Paladins of the West Kingdom: City of Crowns', 'Rozszerzenie do gry Paladins of the West Kingdom, wprowadzające nowe karty, mechaniki i wyzwania.', 1, 4, 90, 3.5),
('Tiny Towns', 'Gra strategiczna, w której gracze budują miasta, zbierając zasoby i umieszczając budynki na swoich planszach.', 1, 6, 45, 2.2),
('Nemesis: Void Seeders', 'Rozszerzenie do gry Nemesis, wprowadzające nową frakcję wrogów - Void Seeders.', 1, 5, 180, 4.5),
('Teotihuacan: Late Preclassic Period', 'Rozszerzenie do gry Teotihuacan, wprowadzające nowe technologie, kapłanów i budynki.', 1, 4, 120, 3.7),
('Robinson Crusoe: Mystery Tales', 'Rozszerzenie do gry Robinson Crusoe, wprowadzające nowe scenariusze i elementy fabularne.', 1, 4, 120, 3.8),
('Gugong', 'Gra strategiczna osadzona w cesarskich Chinach, w której gracze przekupują urzędników, by zdobyć wpływy i bogactwo.', 1, 5, 90, 3.3),
('Trickerion: Legends of Illusion', 'Gra strategiczna, w której gracze wcielają się w magików rywalizujących o sławę i prestiż.', 2, 4, 120, 3.7),
('Orléans', 'Gra planszowa, w której gracze rekrutują robotników, aby rozwijać swoje średniowieczne miasta i zdobywać punkty.', 2, 4, 90, 3.2),
('The Quacks of Quedlinburg: The Herb Witches', 'Rozszerzenie do gry The Quacks of Quedlinburg, wprowadzające nowe składniki i postacie.', 2, 5, 45, 2.2),
('Black Angel', 'Gra strategiczna osadzona w kosmosie, gdzie gracze sterują statkiem kosmicznym, eksplorują planety i walczą z wrogami.', 1, 4, 120, 3.5),
('Raiders of Scythia', 'Gra strategiczna, w której gracze jako wojownicy Scytów rabują wioski, gromadzą zasoby i zdobywają punkty.', 1, 4, 60, 2.8),
('Lisboa', 'Gra ekonomiczna osadzona w XVIII-wiecznej Lizbonie, gdzie gracze odbudowują miasto po trzęsieniu ziemi.', 1, 4, 120, 4.2),
('Atlantis Rising', 'Gra kooperacyjna, w której gracze starają się ocalić Atlantydę przed zatopieniem, zbierając zasoby i budując bramy.', 1, 7, 90, 3.1),
('Heaven & Ale', 'Gra ekonomiczna, w której gracze zarządzają klasztornymi browarami, produkując piwo i zarządzając zasobami.', 2, 4, 60, 3.4),
('Paleo', 'Gra kooperacyjna, w której gracze jako członkowie prehistorycznego plemienia starają się przetrwać, zdobywając pożywienie i walcząc z zagrożeniami.', 2, 4, 60, 2.8),
('Rising Sun', 'Gra strategiczna osadzona w feudalnej Japonii, gdzie gracze rywalizują o dominację poprzez walkę, dyplomację i zdrady.', 3, 5, 90, 3.4),
('Hadara', 'Gra cywilizacyjna, w której gracze rozwijają swoje cywilizacje przez trzy epoki, zdobywając punkty za kulturę, technologię i wojsko.', 2, 5, 60, 2.5),
('Maracaibo', 'Gra strategiczna osadzona w XVII-wiecznych Karaibach, gdzie gracze eksplorują, handlują i walczą o wpływy.', 1, 4, 150, 3.9),
('Alchemists', 'Gra logiczna, w której gracze wcielają się w alchemików, mieszając składniki i odkrywając nowe eliksiry.', 2, 4, 120, 3.5),
('The Taverns of Tiefenthal', 'Gra strategiczna, w której gracze zarządzają karczmami, zatrudniają pracowników i starają się przyciągnąć jak najwięcej klientów.', 2, 4, 60, 2.8),
('Orléans: Invasion', 'Rozszerzenie do gry Orléans, wprowadzające nowe scenariusze, tryby gry i elementy strategiczne.', 2, 5, 120, 3.6),
('The Isle of Cats: Late Arrivals', 'Rozszerzenie do gry The Isle of Cats, wprowadzające dodatkowe karty, plansze i możliwości rozgrywki.', 1, 6, 90, 2.9),
('Viticulture: Visit from the Rhine Valley', 'Rozszerzenie do gry Viticulture, wprowadzające nowe karty gości i możliwości punktacji.', 1, 6, 90, 2.8),
('Gugong: Panjun', 'Rozszerzenie do gry Gugong, dodające nowe komponenty, zasady i wyzwania.', 1, 5, 90, 3.5),
('Paladins of the West Kingdom: Vassals of the West Kingdom', 'Rozszerzenie do gry Paladins of the West Kingdom, wprowadzające nowe elementy i mechaniki.', 1, 4, 90, 3.5),
('Raiders of the North Sea: Fields of Fame', 'Rozszerzenie do gry Raiders of the North Sea, dodające nowe karty, postacie i zasady.', 2, 4, 80, 2.8),
('Teotihuacan: Shadow of Xitle', 'Rozszerzenie do gry Teotihuacan, wprowadzające nowe technologie i budynki.', 1, 4, 120, 3.7),
('The Taverns of Tiefenthal: Open Doors', 'Rozszerzenie do gry The Taverns of Tiefenthal, dodające nowe karty, postacie i zasady.', 2, 4, 60, 2.8),
('Root: The Riverfolk Expansion', 'Rozszerzenie do gry Root, dodające nowe frakcje oraz elementy rozgrywki.', 2, 6, 90, 3.5),
('Great Western Trail: Rails to the North', 'Rozszerzenie do gry Great Western Trail, wprowadzające nowe plansze, karty i możliwości strategiczne.', 2, 4, 150, 3.8),
('Orléans: Trade & Intrigue', 'Rozszerzenie do gry Orléans, wprowadzające nowe karty, plansze i mechaniki związane z handlem i intrygami.', 2, 4, 90, 3.4),
('Cerebria: The Inside World', 'Gra strategiczna, w której gracze wcielają się w emocje walczące o kontrolę nad umysłem.', 1, 4, 120, 3.9),
('Glen More II: Chronicles', 'Gra strategiczna, w której gracze rozwijają swoje klany w Szkocji, zarządzając zasobami i budując osady.', 1, 4, 90, 3.2),
('Raiders of Scythia: The South', 'Rozszerzenie do gry Raiders of Scythia, dodające nowe tereny, zasady i wyzwania.', 1, 4, 60, 2.9),
('Kanban EV', 'Gra strategiczna osadzona w fabryce samochodów elektrycznych, gdzie gracze zarządzają produkcją i logistyką.', 1, 4, 120, 3.8),
('Pandemic: Iberia', 'Gra kooperacyjna osadzona w XIX-wiecznej Hiszpanii, gdzie gracze walczą z epidemiami różnych chorób.', 2, 5, 45, 2.7),
('Inis', 'Gra strategiczna inspirowana mitologią celtycką, w której gracze rywalizują o kontrolę nad wyspą.', 2, 4, 90, 3.0),
('Newton', 'Gra strategiczna, w której gracze wcielają się w XVII-wiecznych naukowców, zdobywając wiedzę i odkrywając nowe teorie.', 1, 4, 90, 3.5),
('Ankh: Gods of Egypt', 'Gra strategiczna osadzona w starożytnym Egipcie, gdzie gracze wcielają się w bogów walczących o dominację.', 2, 5, 90, 3.4),
('Rococo: Deluxe Edition', 'Gra ekonomiczna, w której gracze zarządzają pracowniami krawieckimi w XVIII-wiecznej Francji, przygotowując stroje na bal.', 1, 5, 90, 3.3),
('Barrage', 'Gra strategiczna, w której gracze zarządzają zasobami wodnymi, budując tamy i elektrownie wodne.', 1, 4, 120, 4.0),
('Pax Renaissance', 'Gra strategiczna osadzona w okresie renesansu, gdzie gracze rywalizują o wpływy w Europie poprzez handel, politykę i intrygi.', 2, 4, 60, 3.8),
('Calico', 'Gra logiczna, w której gracze tworzą kolorowe koce, łącząc wzory i przyciągając koty.', 1, 4, 45, 2.2),
('Circadians: First Light', 'Gra strategiczna osadzona w kosmosie, gdzie gracze zarządzają zasobami i eksplorują obce planety.', 1, 4, 90, 3.4),
('Underwater Cities: New Discoveries', 'Rozszerzenie do gry Underwater Cities, wprowadzające nowe karty, zasady i komponenty.', 1, 4, 150, 3.8),
('Troyes', 'Gra strategiczna, w której gracze zarządzają średniowiecznym miastem, wykorzystując kostki do wykonywania akcji.', 2, 4, 90, 3.5),
('Imperial Assault', 'Gra przygodowa osadzona w świecie Gwiezdnych Wojen, gdzie gracze wykonują misje i walczą z przeciwnikami.', 2, 5, 120, 3.2),
('Barrage: The Leeghwater Project', 'Rozszerzenie do gry Barrage, wprowadzające nowe plansze, zasady i wyzwania.', 1, 4, 120, 4.1),
('Onitama', 'Gra logiczna dla dwóch graczy, przypominająca szachy, w której gracze przemieszczają figury według określonych wzorów.', 2, 2, 20, 1.8),
('Carnegie', 'Gra ekonomiczna, w której gracze zarządzają firmami i inwestują w rozwój infrastruktury w XIX-wiecznej Ameryce.', 1, 4, 120, 3.6),
('Smartphone Inc.', 'Gra ekonomiczna, w której gracze zarządzają firmami produkującymi smartfony, rywalizując na globalnym rynku.', 1, 5, 90, 3.2),
('Root: The Clockwork Expansion', 'Rozszerzenie do gry Root, wprowadzające zautomatyzowane frakcje, które mogą być kontrolowane przez graczy lub działać jako AI.', 1, 6, 90, 3.8),
('Lisboa: The Queen\'s Edition', 'Rozszerzona edycja gry Lisboa, w której gracze odbudowują Lizbonę po trzęsieniu ziemi, pożarze i tsunami z 1755 roku.', 1, 4, 120, 4.2),
('The Quest for El Dorado', 'Gra wyścigowa, w której gracze prowadzą ekspedycje przez amazońską dżunglę w poszukiwaniu legendarnego miasta złota.', 2, 4, 60, 2.2),
('Res Arcana', 'Gra karciana, w której gracze wcielają się w magów rywalizujących o władzę nad magicznymi artefaktami.', 2, 4, 60, 2.9),
('Underwater Cities: Essentials', 'Rozszerzenie do gry Underwater Cities, dodające nowe komponenty, karty i zasady do podstawowej rozgrywki.', 1, 4, 150, 3.9),
('Clank! In! Space!', 'Gra przygodowa osadzona w kosmosie, gdzie gracze kradną skarby z międzygalaktycznego statku, starając się uniknąć obudzenia Lorda Eradikusa.', 2, 4, 60, 2.7),
('Cthulhu: Death May Die – Season 2', 'Rozszerzenie do gry Cthulhu: Death May Die, wprowadzające nowe scenariusze, bohaterów i wrogów.', 1, 5, 90, 3.7),
('Cry Havoc', 'Gra strategiczna, w której gracze prowadzą frakcje walczące o kontrolę nad planetą bogatą w zasoby.', 2, 4, 90, 3.5),
('Great Western Trail: Argentina', 'Samodzielna gra oparta na mechanice Great Western Trail, osadzona w Argentynie, gdzie gracze zarządzają hodowlą bydła i transportem.', 2, 4, 150, 3.8),
('Castles of Mad King Ludwig', 'Gra strategiczna, w której gracze budują zamki dla szalonego króla Ludwika II Bawarskiego, starając się spełnić jego kaprysy.', 1, 4, 90, 2.9),
('Everdell: Bellfaire', 'Rozszerzenie do gry Everdell, wprowadzające nowe karty, plansze i mechaniki związane z festiwalem Bellfaire.', 1, 4, 80, 3.1),
('Abyss', 'Gra karciana osadzona w podwodnym królestwie, gdzie gracze rywalizują o władzę, rekrutując lordów i zdobywając perły.', 2, 4, 45, 2.3),
('Food Chain Magnate', 'Gra ekonomiczna, w której gracze zarządzają sieciami restauracji, rywalizując o klientów i rozwój biznesu.', 2, 5, 120, 4.2),
('Endeavor: Age of Sail', 'Gra strategiczna, w której gracze rozwijają swoje imperia morskie, eksplorując, handlując i walcząc o wpływy.', 2, 5, 90, 3.5),
('Paladins of the West Kingdom: City of Crowns', 'Rozszerzenie do gry Paladins of the West Kingdom, wprowadzające nowe mechaniki związane z polityką i dyplomacją.', 1, 4, 90, 3.5),
('Viscounts of the West Kingdom', 'Gra strategiczna, w której gracze zarządzają swoim królestwem, zdobywając wpływy, budując budynki i rekrutując sojuszników.', 1, 4, 90, 3.3),
('The Manhattan Project: Energy Empire', 'Gra strategiczna, w której gracze rozwijają swoje państwa, inwestując w energię, przemysł i technologię.', 1, 5, 120, 3.2),
('Mariposas', 'Gra planszowa, w której gracze kierują migracją motyli monarchów przez Amerykę Północną, starając się zbierać punkty za różne etapy podróży.', 2, 5, 45, 2.2),
('Clinic: Deluxe Edition', 'Gra ekonomiczna, w której gracze zarządzają szpitalem, budując nowe oddziały, zatrudniając personel i lecząc pacjentów.', 1, 4, 120, 3.8),
('Lorenzo il Magnifico', 'Gra strategiczna osadzona w renesansowej Florencji, gdzie gracze rywalizują o wpływy, budując pałace i wspierając artystów.', 2, 4, 90, 3.4),
('Ceylon', 'Gra ekonomiczna, w której gracze zarządzają plantacjami herbaty na Cejlonie, rozwijając uprawy i handlując towarami.', 2, 4, 75, 2.8),
('Clans of Caledonia: New Horizons', 'Rozszerzenie do gry Clans of Caledonia, wprowadzające nowe klany, zasady i elementy strategiczne.', 1, 4, 120, 3.3),
('Rajas of the Ganges', 'Gra strategiczna osadzona w Indiach, gdzie gracze rozwijają swoje prowincje, budując pałace i zarządzając handlem.', 2, 4, 90, 2.9),
('Decrypto', 'Gra towarzyska, w której gracze przekazują zaszyfrowane wiadomości, starając się, by przeciwnicy ich nie odszyfrowali.', 3, 8, 30, 2.1),
('Aeon\'s End: War Eternal', 'Samodzielna gra z serii Aeon\'s End, w której gracze bronią miasta przed inwazją potężnych istot zwanych Nemesis.', 1, 4, 60, 3.3),
('Newton: Great Discoveries', 'Rozszerzenie do gry Newton, wprowadzające nowe karty, mechaniki i możliwości strategiczne.', 1, 4, 90, 3.6),
('Marco Polo II: In the Service of the Khan', 'Kontynuacja gry The Voyages of Marco Polo, w której gracze podróżują po Azji, wykonując misje dla chana.', 2, 4, 120, 3.5),
('Clinic: The Expansion', 'Rozszerzenie do gry Clinic, wprowadzające nowe oddziały, personel i scenariusze.', 1, 4, 120, 3.9),
('Darwin\'s Journey', 'Gra strategiczna, w której gracze podążają śladami Charlesa Darwina, odkrywając nowe gatunki i rozwijając teorie ewolucji.', 1, 4, 120, 3.8),
('Paladins of the West Kingdom: The Age of Artisans', 'Rozszerzenie do gry Paladins of the West Kingdom, wprowadzające nowe mechaniki związane z rzemiosłem i sztuką.', 1, 4, 90, 3.4),
('Praga Caput Regni', 'Gra strategiczna, w której gracze rozwijają średniowieczną Pragę, budując mosty, mury i inne struktury, aby zdobywać punkty zwycięstwa.', 1, 4, 120, 3.7);